/** Minimum manifest version this runtime supports. */
export const MANIFEST_VERSION_MIN = 1;
/** Maximum manifest version this runtime supports. */
export const MANIFEST_VERSION_MAX = 1;

/** Top-level manifest generated by `tgimg build`. */
export interface TgImgManifest {
  version: number;
  generated_at: string;
  profile: string;
  base_path: string;
  build_info?: { workers: number; pool_entry_kb: number };
  assets: Record<string, TgImgAsset>;
  stats: TgImgStats;
}

/** A single asset with its original info, thumbhash, and variants. */
export interface TgImgAsset {
  original: {
    width: number;
    height: number;
    format: string;
    size: number;
    has_alpha: boolean;
  };
  thumbhash: string; // base64
  aspect_ratio: number;
  /** Average color of original [R, G, B] (0–255). Optional, set by CLI. */
  avg_color?: [number, number, number];
  variants: TgImgVariant[];
}

/** One encoded variant of an asset (specific format + dimensions). */
export interface TgImgVariant {
  format: string;  // "avif" | "webp" | "jpeg" | "png"
  width: number;
  height: number;
  size: number;
  hash: string;
  path: string;
}

/** Build statistics. */
export interface TgImgStats {
  total_input_bytes: number;
  total_output_bytes: number;
  total_assets: number;
  total_variants: number;
  skipped_regress?: number;
}

/** Props for the <TgImg /> component. */
export interface TgImgProps {
  /** Asset key from manifest (e.g. "promo/banner"). */
  src: string;

  /** Alt text for accessibility. */
  alt: string;

  /** Explicit width in CSS pixels. If omitted, fills container. */
  width?: number;

  /** Explicit height in CSS pixels. If omitted, computed from ratio. */
  height?: number;

  /** Aspect ratio override (width/height). Computed from manifest if omitted. */
  ratio?: number;

  /** Object-fit mode. Default: "cover". */
  fit?: 'cover' | 'contain' | 'fill' | 'none';

  /** Border radius in px or CSS value. */
  radius?: number | string;

  /** If true, load eagerly and prefetch. Default: false (lazy). */
  priority?: boolean;

  /** Additional CSS class for the container. */
  className?: string;

  /** Inline styles for the container. */
  style?: React.CSSProperties;

  /**
   * Transition mode for placeholder → image swap.
   *
   * - `"auto"` (default) — instant for small images (< 80 000 px²),
   *   reveal for large.
   * - `"instant"` — hard swap after `img.decode()`, no animation.
   * - `"reveal"` — blur-to-sharp reveal (160 ms).
   * - `"off"` — no transition at all, image appears on load.
   *
   * @default "auto"
   */
  transition?: import('./transition').TransitionMode;

  /**
   * Chroma attenuation for the thumbhash placeholder.
   * 0 = grayscale, 1 = full color.
   * When omitted, auto-selected per transition mode (0.25 instant, 0.10 reveal).
   * @default 0.15
   */
  placeholderChroma?: number;

  /** Base URL prefix for asset paths. Default: manifest base_path. */
  baseUrl?: string;

  /** Called when the full image has loaded and decoded. */
  onLoad?: () => void;

  /** Called on error. */
  onError?: (error: Error) => void;
}

/** Supported image formats in priority order. */
export type ImageFormat = 'avif' | 'webp' | 'jpeg' | 'png';

/** Format detection result. */
export interface FormatSupport {
  avif: boolean;
  webp: boolean;
  jpeg: boolean;
  png: boolean;
}
